=== eiffel-community/eiffel-intelligence/src/main/resources/schemas/subscription_schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"definitions": {},
	"properties": {
		"created": {
			"type": "long"
		},
		"notificationMeta": {
			"type": "string"
		},
		"notificationType": {
			"type": "string"
		},
		"emailSubject": {
		"type": "string"
		},
		"restPostBodyMediaType": {
		"type": "string"
		},
		"notificationMessageKeyValues": {
			"items": {
				"properties": {
					"formkey": {
						"type": "string"
					},
					"formvalue": {
						"type": "string"
					}
				},
				"type": "object"
			},
			"type": "array"
		},
		"repeat": {
			"type": "boolean"
		},
		"requirements": {
			"items": {
				"properties": {
					"conditions": {
						"items": {
							"properties": {
								"jmespath": {
									"type": "string"
								}
							},
							"type": "object"
						},
						"type": "array"
					}
				},
				"type": "object"
			},
			"type": "array"
		},
		"subscriptionName": {
			"type": "string"
		},
		"userName": {
			"type": "string"
		},
		"password": {
			"type": "string"
		},
		"ldapUserName": {
			"type": "string"
		}
	},
	"type": "object"
}

=== eiffel-community/eiffel-intelligence/src/test/resources/subscriptionForMapNotification.json
{
  "subscriptionName": "Subscription_1",
  "userName" : "DEF",
  "repeat": false,
  "created": "data-time",
  "notificationType": "MAIL",
  "notificationMeta": "example@ericsson.com",
  "restPostBodyMediaType": "application/json",
  "notificationMessageKeyValues": [
    {
      "formkey": "",
      "formvalue": "{conclusion:testCaseExecutions[?outcome.conclusion == 'SUCCESSFUL' && outcome.id=='TC5'] | [0].outcome.conclusion,id:testCaseExecutions[?outcome.conclusion == 'SUCCESSFUL' && outcome.id=='TC5'] | [0].outcome.id}"
    }
  ],
  "requirements": [
    {
      "type": "ARTIFACT_1",
      "conditions": [
        {
          "jmespath": "gav.groupId=='com.mycompany.myproduct'"
        },
        {
          "jmespath": "testCaseExecutions[?testCase.conclusion == 'SUCCESSFUL' && testCase.id=='TC5']"
        }
      ]
    },
    {
      "type": "ARTIFACT_1",
      "conditions": [
        {
          "jmespath": "gav.groupId=='com.mycompany.myproduct'"
        },
        {
          "jmespath": "testCaseExecutions[?testCaseStartedEventId == '13af4a14-f951-4346-a1ba-624c79f10e98']"
        }
      ]
    }
  ]
}
