=== eiffel-community/eiffel-intelligence/src/main/resources/schemas/subscription_schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"definitions": {},
	"properties": {
		"created": {
			"type": "long"
		},
		"notificationMeta": {
			"type": "string"
		},
		"notificationType": {
			"type": "string"
		},
		"emailSubject": {
		"type": "string"
		},
		"restPostBodyMediaType": {
		"type": "string"
		},
		"notificationMessageKeyValues": {
			"items": {
				"properties": {
					"formkey": {
						"type": "string"
					},
					"formvalue": {
						"type": "string"
					}
				},
				"type": "object"
			},
			"type": "array"
		},
		"repeat": {
			"type": "boolean"
		},
		"requirements": {
			"items": {
				"properties": {
					"conditions": {
						"items": {
							"properties": {
								"jmespath": {
									"type": "string"
								}
							},
							"type": "object"
						},
						"type": "array"
					}
				},
				"type": "object"
			},
			"type": "array"
		},
		"subscriptionName": {
			"type": "string"
		},
		"userName": {
			"type": "string"
		},
		"password": {
			"type": "string"
		},
		"ldapUserName": {
			"type": "string"
		}
	},
	"type": "object"
}

=== eiffel-community/eiffel-intelligence/src/test/resources/subscription_CLME.json
[
  {
  "created" : "2017-07-26",
  "notificationMeta" : "http://127.0.0.1:3000/ei/test_subscription_rest",
  "notificationType" : "REST_POST",
  "restPostBodyMediaType" : "application/x-www-form-urlencoded",
  "notificationMessageKeyValues" : [
    {
      "formkey" : "e",
      "formvalue" : "{parameter: [{ name: 'jsonparams', value : to_string(@) }, { name: 'runpipeline', value : 'mybuildstep' }]}"
    }
  ],
  "repeat" : false,
  "requirements" : [
    {
      "conditions" : [
        {
          "jmespath" : "meta.type == 'EiffelConfidenceLevelModifiedEvent'"
        },
        {
          "jmespath" : "data.name == 'stable' && data.value =='SUCCESS'"
        }
      ],
      "type" : "Event_copy"
    }
  ],
  "subscriptionName" : "Single_CLME_Subscription_Test",
  "userName" : "ABC"
}
]

=== eiffel-community/eiffel-intelligence/src/functionaltests/resources/ValidSubscription.json
[
  {
    "subscriptionName": "mySubscription",
    "userName" : "DEF",
    "repeat": false,
    "created": "data-time",
    "notificationType": "REST_POST",
    "notificationMeta": "http://127.0.0.1:3000/ei/test_subscription_rest",
    "restPostBodyMediaType": "application/json",
    "notificationMessageKeyValues" : [
      {
        "formkey" : "",
        "formvalue" : "@"
      }
    ],

    "requirements": [
      {
        "type": "ARTIFACT_1",
        "conditions": [
          {"jmespath": "gav.groupId=='com.mycompany.myproduct'"},
          {"jmespath": "testCaseExecutions[?testCase.conclusion == 'SUCCESSFUL' && testCase.id=='TC5']"}
        ]

      },
      {
        "type": "ARTIFACT_1",
        "conditions": [
          {"jmespath": "gav.groupId=='com.mycompany.myproduct'"},
          {"jmespath": "testCaseExecutions[?testCaseStartedEventId == '13af4a14-f951-4346-a1ba-624c79f10e98']"}
        ]

      }
    ]
  }
]

=== eiffel-community/eiffel-intelligence/src/functionaltests/resources/subscription_multiple.json
[
  {
    "subscriptionName": "Subscription_Mail",
    "userName": "DEF",
    "repeat": false,
    "created": "data-time",
    "notificationType": "MAIL",
    "notificationMeta": "example@ericsson.com",
    "restPostBodyMediaType": "application/json",
    "notificationMessageKeyValues": [
      {
        "formkey": "",
        "formvalue": "@"
      }
    ],
    "requirements": [
      {
        "type": "ARTIFACT_1",
        "conditions": [
          {
            "jmespath": "gav.groupId=='com.mycompany.myproduct'"
          },
          {
            "jmespath": "testCaseExecutions[?testCase.conclusion == 'SUCCESSFUL' && testCase.id=='TC5']"
          }
        ]
      },
      {
        "type": "ARTIFACT_1",
        "conditions": [
          {
            "jmespath": "gav.groupId=='com.mycompany.myproduct'"
          },
          {
            "jmespath": "testCaseExecutions[?testCaseStartedEventId == '13af4a14-f951-4346-a1ba-624c79f10e98']"
          }
        ]
      }
    ]
  },
  {
    "subscriptionName": "Subscription_Rest_Params_in_Head",
    "userName": "DEF",
    "repeat": false,
    "created": "data-time",
    "notificationType": "REST_POST",
    "notificationMeta": "http://${rest.host}:${rest.port}${rest.endpoint}",
    "restPostBodyMediaType": "application/json",
    "notificationMessageKeyValues": [
      {
        "formkey" : "",
        "formvalue" : "@"
      }
    ],
    "requirements": [
      {
        "type": "ARTIFACT_1",
        "conditions": [
          {
            "jmespath": "gav.groupId=='com.mycompany.myproduct'"
          },
          {
            "jmespath": "testCaseExecutions[?testCase.conclusion == 'SUCCESSFUL' && testCase.id=='TC5']"
          }
        ]
      },
      {
        "type": "ARTIFACT_1",
        "conditions": [
          {
            "jmespath": "gav.groupId=='com.mycompany.myproduct'"
          },
          {
            "jmespath": "testCaseExecutions[?testCaseStartedEventId == '13af4a14-f951-4346-a1ba-624c79f10e98']"
          }
        ]
      }
    ]
  },
  {
    "subscriptionName": "Subscription_Rest_Auth_Params_in_Head",
    "userName": "DEF",
    "repeat": false,
    "created": "data-time",
    "notificationType": "REST_POST",
    "notificationMeta": "http://${rest.host}:${rest.port}${rest.endpoint.auth}",
    "restPostBodyMediaType": "application/x-www-form-urlencoded",
    "notificationMessageKeyValues" : [
      {
        "formkey" : "json",
        "formvalue" : "{parameter: [{ name: 'parameter', value : testCase.conclusion }]}"
      },
      {
        "formkey" : "Authorization",
        "formvalue" : "Basic TXkgQ2F0IFNtdWxhbiBMaWtlcyBUbyBmZXRjaCBjb21wdXRlciBtb3VzZXM="
      }
    ],

    "requirements": [
      {
        "type": "ARTIFACT_1",
        "conditions": [
          {"jmespath": "gav.groupId=='com.mycompany.myproduct'"},
          {"jmespath": "testCaseExecutions[?testCase.conclusion == 'SUCCESSFUL' && testCase.id=='TC5']"}
        ]

      },
      {
        "type": "ARTIFACT_1",
        "conditions": [
          {"jmespath": "gav.groupId=='com.mycompany.myproduct'"},
          {"jmespath": "testCaseExecutions[?testCaseStartedEventId == '13af4a14-f951-4346-a1ba-624c79f10e98']"}
        ]
      }
    ]
  }
]

=== eiffel-community/eiffel-intelligence/src/test/resources/artifactRequirementSubscription.json
{
    "created": "2017-07-26",
    "notificationMeta": "http://127.0.0.1:3000/ei/test_subscription_rest",
    "notificationType": "REST_POST",
    "restPostBodyMediaType": "application/json",
    "notificationMessageKeyValues": [
      {
        "formkey": "",
        "formvalue": "@"
      }
    ],
    "repeat": false,
    "requirements": [
      {
        "conditions": [         
          {
            "jmespath": "incomplete_path_contains(@, 'issues.id','JIRA-1234')"
          }
        ],
        "type": "ARTIFACT_1"
      }
    ],
    "subscriptionName": "artifactRequirementSubscription",
    "userName": "ABC"
  }

=== eiffel-community/eiffel-intelligence/src/functionaltests/resources/subscription_single_ttlTest.json
[
{
    "subscriptionName": "Subscription_Test_3",
    "repeat": false,
    "created": 1523473956269,
    "notificationType": "REST_POST",
    "notificationMeta": "http://eiffel-jenkins3:8080/job/ei-artifact-triggered-job/build",
    "restPostBodyMediaType": "application/x-www-form-urlencoded",
    "notificationMessageKeyValues": [
      {
        "formkey": "json",
        "formvalue": "{parameter: [{ name: 'jsonparams', value : to_string(@) }]}"
      }
    ],
    "requirements": [
      {
        "conditions": [
          {
            "jmespath": "identity=='pkg:maven/com.mycompany.myproduct/artifact-name@1.0.0'"
          }
        ]
      }
    ]
  }
]

=== eiffel-community/eiffel-intelligence/src/functionaltests/resources/subscriptions_multiple_updated.json
[
  {
    "subscriptionName": "Subscription_Test_1",
    "repeat": false,
    "created": 1523473956269,
    "notificationType": "MAIL",
    "notificationMeta": "mail1@company.com",
    "restPostBodyMediaType": "application/x-www-form-urlencoded",
    "notificationMessageKeyValues": [
      {
        "formkey": "json",
        "formvalue": "{parameter: [{ name: 'jsonparams', value : to_string(@) }]}"
      }
    ],
    "requirements": [
      {
        "conditions": [
          {
            "jmespath": "split(identity, '/') | [1] =='com.mycompany.myproduct'"
          }
        ]
      }
    ]
  },
  {
    "subscriptionName": "Subscription_Test_2",
    "repeat": false,
    "created": 1523473956269,
    "notificationType": "MAIL",
    "notificationMeta": "mail2@company.com",
    "restPostBodyMediaType": "application/x-www-form-urlencoded",
    "notificationMessageKeyValues": [
      {
        "formkey": "json",
        "formvalue": "{parameter: [{ name: 'jsonparams', value : to_string(@) }]}"
      }
    ],
    "requirements": [
      {
        "conditions": [
          {
            "jmespath": "split(identity, '/') | [1] =='com.mycompany.myproduct'"
          }
        ]
      }
    ]
  },
  {
    "subscriptionName": "Subscription_Test_3",
    "repeat": false,
    "created": 1523473956269,
    "notificationType": "MAIL",
    "notificationMeta": "mail3@company.com",
    "restPostBodyMediaType": "application/x-www-form-urlencoded",
    "notificationMessageKeyValues": [
      {
        "formkey": "json",
        "formvalue": "{parameter: [{ name: 'jsonparams', value : to_string(@) }]}"
      }
    ],
    "requirements": [
      {
        "conditions": [
          {
            "jmespath": "split(identity, '/') | [1] =='com.mycompany.myproduct'"
          }
        ]
      }
    ]
  }
]

=== eiffel-community/eiffel-intelligence/src/functionaltests/resources/subscription_single.json
[
  {
    "created": "2017-07-26",
    "notificationMeta": "http://127.0.0.1:3000/ei/test_subscription_rest",
    "notificationType": "REST_POST",
    "restPostBodyMediaType": "application/x-www-form-urlencoded",
    "notificationMessageKeyValues": [
      {
        "formkey": "e",
        "formvalue": "{parameter: [{ name: 'jsonparams', value : to_string(@) }, { name: 'runpipeline', value : 'mybuildstep' }]}"
      }
    ],
    "repeat": false,
    "requirements": [
      {
        "conditions": [
          {
            "jmespath": "gav.groupId=='com.mycompany.myproduct'"
          },
          {
            "jmespath": "testCaseExecutions[?testCase.conclusion == 'SUCCESSFUL' && testCase.id=='TC5']"
          }
        ],
        "type": "ARTIFACT_1"
      },
      {
        "conditions": [
          {
            "jmespath": "gav.groupId=='com.mycompany.myproduct'"
          },
          {
            "jmespath": "testCaseExecutions[?testCaseStartedEventId == '13af4a14-f951-4346-a1ba-624c79f10e98']"
          }
        ],
        "type": "ARTIFACT_1"
      }
    ],
    "subscriptionName": "Subscription_Test",
    "userName": "ABC"
  }
]

=== eiffel-community/eiffel-intelligence/src/functionaltests/resources/subscriptionRepeatHandler.json
[
  {
    "created" : "2017-07-26",
    "notificationMeta" : "http://127.0.0.1:3000/ei/test_subscription_rest",
    "notificationType" : "REST_POST",
    "restPostBodyMediaType" : "application/x-www-form-urlencoded",
    "notificationMessageKeyValues" : [
      {
        "formkey" : "e",
        "formvalue" : "{parameter: [{ name: 'jsonparams', value : to_string(@) }, { name: 'runpipeline', value : 'mybuildstep' }]}"
      }
    ],
    "repeat" : true,
    "requirements" : [
      {
        "conditions" : [
          {
            "jmespath" : "test_suite[?test_case.test_data.tracker == 'My Test Management System' && test_case.test_data.id == 'TC-1234']"
          }
        ],
        "type" : "TEST_EXECUTION_1"
      }
    ],
    "subscriptionName" : "Subscription_Test",
    "userName" : "ABC"
  }
]
